In [11]:
import sys
sys.path.append('../')

In [12]:
import numpy as np

In [13]:
X = [  1,   2,   3,   4,   5]
Y = [2.1, 3.9, 4.2, 5.5, 6.9]

In [14]:
X = np.array(X)
Y = np.array(Y)

In [15]:
K_fs = [lambda x : x, lambda _ : 1]

In [16]:
from min_sqrs import min_sqrs

In [17]:
K = min_sqrs(X, K_fs, Y)
K

array([[1.12],
       [1.16]])

In [18]:
f     = lambda x : K[0]*x + K[1]
vec_f = np.vectorize(f)

In [19]:
vec_f(X)

array([2.28, 3.4 , 4.52, 5.64, 6.76])

In [20]:
Y

array([2.1, 3.9, 4.2, 5.5, 6.9])