In [1]:
import sys
sys.path.append('../')

In [2]:
import numpy as np

In [3]:
X = [  1,   2,   3,   4,   5]
Y = [2.1, 3.9, 4.2, 5.5, 6.9]

In [4]:
X = np.array(X)
Y = np.array(Y)

In [5]:
K_fs = [lambda x : x, lambda _ : 1]

In [6]:
from min_sqrs import min_sqrs

In [7]:
K = min_sqrs(X, K_fs, Y)
K

array([[1.12],
       [1.16]])

In [8]:
f     = lambda x : K[0]*x + K[1]
vec_f = np.vectorize(f)

In [9]:
vec_f(X)

array([2.28, 3.4 , 4.52, 5.64, 6.76])

In [10]:
Y

array([2.1, 3.9, 4.2, 5.5, 6.9])

In [11]:
from min_sqrs import square_error, mean_square_error

In [12]:
square_error(Y, vec_f(X))

0.42400000000000004

In [13]:
mean_square_error(Y, vec_f(X))

0.08480000000000001